//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArqueoCajaDet
    {
        public int idArqueoCajaDet { get; set; }
        public int idArqueoCaja { get; set; }
        public int idMoneda { get; set; }
        public int idDenominacion { get; set; }
        public double cantidad { get; set; }
        public double subtotal { get; set; }
    
        public virtual ArqueoCaja ArqueoCaja { get; set; }
        public virtual Denominacion Denominacion { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
