//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int idRegistroGastos { get; set; }
        public int idKermesse { get; set; }
        public int idCatGastos { get; set; }
        public System.DateTime fechaGasto { get; set; }
        public string concepto { get; set; }
        public double monto { get; set; }
        public int usuarioCreacion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public int usuarioModificacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public int usuarioEliminacion { get; set; }
        public Nullable<System.DateTime> fechaEliminacion { get; set; }
        public int estado { get; set; }
    
        public virtual CategoriaGasto CategoriaGasto { get; set; }
        public virtual Kermesse Kermesse { get; set; }
    }
}
