//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoComunidad
    {
        public int idIngresoComunidad { get; set; }
        public int idKermesse { get; set; }
        public int idComunidad { get; set; }
        public int idProducto { get; set; }
        public int cantProductos { get; set; }
        public int totalBonos { get; set; }
        public int usuarioCreacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<int> usuarioModificacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> usuarioEliminacion { get; set; }
        public Nullable<System.DateTime> fechaEliminicacion { get; set; }
    
        public virtual Comunidad Comunidad { get; set; }
        public virtual IngresoComunidadDet IngresoComunidadDet { get; set; }
        public virtual Kermesse Kermesse { get; set; }
    }
}
