//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoComunidadDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngresoComunidadDet()
        {
            this.IngresoComunidads = new HashSet<IngresoComunidad>();
        }
    
        public int idIngresoComunidadDet { get; set; }
        public int idIngresoComunidad { get; set; }
        public int idBono { get; set; }
        public string denominacion { get; set; }
        public int cantidad { get; set; }
        public double subtotalBono { get; set; }
    
        public virtual ControlBono ControlBono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoComunidad> IngresoComunidads { get; set; }
    }
}
