//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolOpcione
    {
        public int idRolOpciones { get; set; }
        public int tblRolidRol { get; set; }
        public int tblOpcionesidOpciones { get; set; }
    
        public virtual Opcione Opcione { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
