//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasaCambio
    {
        public int idTasaCambio { get; set; }
        public System.DateTime fecha { get; set; }
        public int estado { get; set; }
        public int idMonedaO { get; set; }
        public int idTasaCambioDetalle { get; set; }
        public int idMonedaC { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual TasaCambioDetalle TasaCambioDetalle { get; set; }
    }
}
